# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MsJ-tiNgDojrrapcnUY2ZD3AmX_7M9tV
"""

!pip install -U langchain langchain-community langchain-text-splitters pypdf

from google.colab import files
files.upload()

!pip install -U langchain langchain-community langchain-text-splitters pypdf

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from datetime import datetime

pdf_files = ["paper1_large.pdf", "notes1_large.pdf"]

documents = []

for file in pdf_files:
    loader = PyPDFLoader(file)
    docs = loader.load()
    documents.extend(docs)

print("✅ Total pages loaded:", len(documents))

splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

chunks = splitter.split_documents(documents)

print("✅ Total chunks created:", len(chunks))

for chunk in chunks:
    meta = chunk.metadata

    chunk.metadata = {
        "filename": meta.get("source", "").split("/")[-1],
        "page_number": meta.get("page", -1),
        "upload_date": datetime.now().strftime("%Y-%m-%d"),
        "source_type": "textbook"
    }

print("✅ Metadata added")

def filter_chunks(chunks, **filters):
    result = []

    for chunk in chunks:
        match = True
        for key, value in filters.items():
            if chunk.metadata.get(key) != value:
                match = False
                break

        if match:
            result.append(chunk)

    return result

filtered = filter_chunks(
    chunks,
    filename="paper1_large.pdf",
    page_number=0
)

print("✅ Filtered chunks:", len(filtered))

if filtered:
    print("\n📄 Sample Content:\n")
    print(filtered[0].page_content[:300])

    print("\n📌 Metadata:\n")
    print(filtered[0].metadata)